name: C/C++ CI

on:
  [push, pull_request]

jobs:   
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11.4
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.4
        cache: 'pip'
    # - name: Cache Dependencies
    #   id: cache-dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
          
    - name: Install dependencies
      # if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Install CMake
      run: |
        choco install cmake
    - name: Install Ninja
      run: |
        choco install ninja
    - name: Install OpenCV
      run: |
        choco install opencv
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        modules: 'qtmultimedia'
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Setup build environment with Ninja
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Relese 
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Build with Ninja
      run: cmake --build ./build --config Release
    - name: Test
      run: |
        ctest -C build --verbose --test-dir build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: build/345Application.exe
        
  run:
    needs: build
    runs-on: windows-latest
    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
      - name: Run Executable
        run: |
          ./345Application.exe

  code-coverage:
    needs: build
    runs-on: windows-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Setup Python
      #   uses: actions/setup-python@v4.7.0
      #   with:
      #     python-version: 3.10
      - name: Install C++ compiler
        run: |
          choco install visualcpp-build-tools -y
        shell: powershell
      - name: Install gcovr
        run: |
          pip install gcovr
        shell: powershell
      - name: Generate Code Coverage Report (Debug)
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-g"
        working-directory: ${{github.workspace}}
      
      - name: Build with Ninja (Debug)
        run: cmake --build ${{github.workspace}}/tests
        working-directory: ${{github.workspace}}
      - name: Tests (Debug)
        run: |
          g++ --coverage ${{github.workspace}}/tests/test.cpp  ${{github.workspace}}/src/text_to_speech/ttsCall.cpp -o ${{github.workspace}}/coverage/coverage_info -lwinmm
          gcovr -r ${{github.workspace}} --xml -o ${{github.workspace}}/coverage/coverage_info.xml
          working-directory: ${{github.workspace}}
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ${{github.workspace}}/coverage/coverage_info.xml
          

    
