name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Create Executable
      run: |
        cd build
        ninja
  run:
    runs-on: windows-latest
    steps:
    - name: Run
      run: |
        cd build
        ./HandApp.exe
  
