name: C/C++ CI

on:
  [push, pull_request]

jobs:   
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11.4
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.4
        cache: 'pip'
    # - name: Cache Dependencies
    #   id: cache-dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
          
    - name: Install dependencies
      # if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Install CMake
      run: |
        choco install cmake
    - name: Install Ninja
      run: |
        choco install ninja
    - name: Install OpenCV
      run: |
        choco install opencv
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        modules: 'qtmultimedia'
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Setup build environment with Ninja
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=ON
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Build with Ninja
      run: cmake --build ./build --config RelWithDebInfo
    - name: Test
      run: |
        ctest -C build --verbose --test-dir build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: build/345Application.exe
        
  run:
    needs: build
    runs-on: windows-latest
    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
      - name: Run Executable
        run: |
          ./345Application.exe

  code-coverage:
    needs: run
    runs-on: windows-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Setup Python
      #   uses: actions/setup-python@v4.7.0
      #   with:
      #     python-version: 3.10
      - name: Setup OpenCppCoverage and add to Path
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
          
      - name: Install C++ compiler
        run: |
          choco install visualcpp-build-tools -y
        shell: powershell
      - name: Install gcovr
        run: |
          pip install gcovr
        shell: powershell
      - name: Tests
        working-directory: ${{github.workspace}}
        run: |
              mkdir coverage
              "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --export_type cobertura:coverage\coverage1.xml build\build-cosc345-Desktop_x86_windows_msvc2022_pe_64bit-RelWithDebInfo\345Application.exe --modules build\build-cosc345-Desktop_x86_windows_msvc2022_pe_64bit-RelWithDebInfo\345Application.exe --sources=cosc345\src   
            # ls -R
            # g++ --coverage tests/test.cpp src/text_to_speech/ttscall.cpp -o coverage1 -lwinmm
            # ./coverage1
            # ls -R
            # gcovr -r ./ --xml -o coverage.xml
            # ls -R
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: coverage\coverage1.xml
        #     & "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --export_type cobertura:coverage\coverage1.xml build\build-cosc345-Desktop_x86_windows_msvc2022_pe_64bit-RelWithDebInfo\345Application.exe --modules build\build-cosc345-Desktop_x86_windows_msvc2022_pe_64bit-RelWithDebInfo\345Application.exe --sources=cosc345\src   
            
        #     #g++ --coverage ${{github.workspace}}/tests/test.cpp  ${{github.workspace}}/src/text_to_speech/ttsCall.cpp -o ${{github.workspace}}/coverage/execoverage -lwinmm
        #     #${{github.workspace}}/coverage/execoverage
        #     #gcovr -r ${{github.workspace}} --xml -o ${{github.workspace}}/coverage/coverage_info.xml
        # - name: Upload coverage report to Codecov
        #   uses: codecov/codecov-action@v3
        #   env:
        #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        #   with:
        #     files: ${{github.workspace}}/coverage/coverage_info.xml
            
  
      
