name: C/C++ CI

on:
  [push, pull_request]

jobs:
  setup-workspace:
    runs-on: windows-latest
    steps:
    - name: Create workspace
      run: |
        mkdir ${{ runner.workspace }}/dependencies
        
  build: 
    needs: setup-workspace
    runs-on: windows-latest
    steps:
    - name: Install CMake
      run: |
        choco install cmake
    - name: Install Ninja
      run: |
        choco install ninja
    - name: Setup build environment
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        
    - name: Build with Ninja
      run: cmake --build ./build

  install-python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.10
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install tts
        
  run:
    needs: [build, install-python]
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: |
          mv ${{ runner.workspace }}/dependencies/* .
      - name: Run
        run: |
          cd build
          ./HandApp.exe

  codecov:
    needs: run
    runs-on: windows-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore dependencies
        run: |
          mv ${{ runner.workspace }}/dependencies/* .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  coverity-analysis:
    runs-on: windows-latest
    steps:
      # ... other steps for building and running Coverity analysis ...
      
      - name: Display Coverity Badge
        run: echo "![Coverity Analysis Status](https://scan.coverity.com/projects/28987/badge.svg)" >> README.md
