name: C/C++ CI

on:
  [push, pull_request]

jobs:   
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11.4
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.4
        cache: 'pip'
    # - name: Cache Dependencies
    #   id: cache-dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
          
    - name: Install dependencies
      # if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Install CMake
      run: |
        choco install cmake
    - name: Install Ninja
      run: |
        choco install ninja
    - name: Install OpenCV
      run: |
        choco install opencv
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        modules: 'qtmultimedia'
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Setup build environment with Ninja
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=ON
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Build with Ninja
      run: cmake --build ./build --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: build/345Application.exe
    - name: Upload Test Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-executable
        path: build/Tests.exe
        
  run:
    needs: build
    runs-on: windows-latest
    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
      - name: Run Executable
        run: |
          ./345Application.exe

  code-coverage:
    needs: run
    runs-on: windows-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
      - name: Download Test Executable
        uses: actions/download-artifact@v3
        with:
          name: test-executable
      - name: Run Executable (testing to see if it works)
        run: |
            ./345Application.exe
      - name: Run Test Executable (testing to see if it works)
        run: |
            ./Tests.exe
      - name: Setup OpenCppCoverage and add to Path
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Tests
        run: |
              & "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --export cobertura:coverage\coverage1.xml 345Application.exe --modules=D:\a\cosc345\cosc345 --sources=cosc345\src 
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: coverage\coverage1.xml
  
      
