name: Codecov

on:
  [push, pull_request]

jobs:   
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: List files
      run: |
          ls
          ls coverage
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_MAX_REPORT_AGE: off
      with:
          files: coverage\coverage_info.xml
    - name: Upload test coverage report to Codecov
      uses: codecov/codecov-action@v2
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_MAX_REPORT_AGE: off
      with:
          files: coverage\coverage_tests.xml
              
              #coverage\coverage_tests.xml
