name: Codecov

on:
  [push, pull_request]

jobs:   
  build: 
    runs-on: windows-latest
    steps:
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
          files: coverage\coverage_info.xml
    - name: Upload test coverage report to Codecov
      uses: codecov/codecov-action@v2
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
          files: coverage\coverage_tests.xml
              
              #coverage\coverage_tests.xml
